resources:
  - name: myGitRepo
    type: GitRepo
    configuration:
      gitProvider: ranjithr_github
      path: ranjithrs/carbot
      branches:
        include: master
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: CarApp
      buildNumber: 1          
pipelines:  
  - name: basic_pipeline
    configuration:
      environmentVariables:
        readOnly:
          myReadEnvVariable: "hello"  
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myGitRepo
          outputResources:
            - name: myBuildInfo             
        execution:
          onExecute:
            - if [ -z $pipeline_var ]; then add_pipeline_variables pipeline_var=1; else echo $pipeline_var; fi
            - if [ -z $app_version ]; then add_pipeline_variables app_version=1.0.0; else app_version=$((bump_semver $app_verision minor)); fi
            - write_output myBuildInfo "buildNumber=$app_version"
            - add_run_variables run_var="hello"
      - name: step_2
        type: Bash
        configuration:
          inputResources:
            - name: myBuildInfo            
          runtime:
            type: image
            image:
              auto:
                language: java
                versions: ['11']
        execution:
          onExecute:
            - if [[ $(($pipeline_var % 2)) -eq 0 ]]; then run_var+=" world"; else run_var+=" universe"; fi
            - echo $run_var  
            - echo $res_myBuildInfo_buildNumber
            - add_pipeline_variables pipeline_var=$((pipeline_var+1))

      - name: step_3
        type: Bash
        configuration:
          environmentVariables:
            env_var1: "hello"
          inputSteps:
            - name: step_2
        execution:
          onExecute:
            - add_run_variables step3_var="1"
            - echo $env_var1

      - name: step_4
        type: Bash
        configuration:
          inputSteps:
            - name: step_2
        execution:
          onExecute:
            - add_run_variables step4_var="1"
      - name: step_5
        type: Bash
        configuration:
          inputSteps:
            - name: step_3
            - name: step_4         
        execution:
          onExecute:
            - echo "step 5"   
      - name: step_6
        type: Bash
        configuration:
          environmentVariables:
            something: $run_number
          inputSteps:
            - name: step_5
        execution:
          onExecute:
            - echo $something  
